import streamlit as st
import requests
from PIL import Image
import sys
import os
import json
import datetime
from fpdf import FPDF

# 1. Function to generate the Academic Research PDF with Charts
def create_pdf(report_data):
    from fpdf import FPDF
    import matplotlib
    matplotlib.use('Agg') # Ensure matplotlib runs in the background without opening windows
    import matplotlib.pyplot as plt
    import tempfile
    import os
    
    class ResearchPaperPDF(FPDF):
        def header(self):
            self.set_font("Times", "B", 10)
            self.cell(0, 5, txt="Journal of Truth Verification & Intelligence", ln=True, align="L")
            self.set_font("Times", "", 9)
            date_str = str(report_data.get("timestamp", ""))[:4] 
            self.cell(0, 5, txt=f"ISSN: 2026-XXXX | Volume 1 Issue 1 Year {date_str}", ln=True, align="L")
            self.set_line_width(0.3)
            self.line(15, 22, 195, 22)
            self.ln(10)

        def footer(self):
            self.set_y(-15)
            self.set_font("Times", "I", 8)
            self.cell(0, 10, f"Page {self.page_no()}", 0, 0, 'C')

    pdf = ResearchPaperPDF(format="A4")
    pdf.add_page()
    pdf.set_margins(15, 25, 15)
    pdf.set_auto_page_break(auto=True, margin=20)
    
    def sanitize(text):
        if not text: return ""
        clean_text = str(text).encode('latin-1', 'replace').decode('latin-1')
        words = clean_text.split()
        safe_words = [w if len(w) <= 65 else w[:62] + "..." for w in words]
        return " ".join(safe_words)
    
    # --- PAPER TITLE & ABSTRACT ---
    pdf.set_font("Times", "B", 16)
    pdf.multi_cell(0, 8, txt="Research Report on Artificial Intelligence Automated Verification", align="C")
    pdf.ln(3)
    
    pdf.set_font("Times", "", 11)
    pdf.cell(0, 6, txt="Generated by: Truth Intelligence System", ln=True, align="C")
    pdf.ln(8)
    
    pdf.set_font("Times", "B", 12)
    pdf.cell(0, 6, txt="Abstract", ln=True, align="C")
    pdf.set_font("Times", "", 11)
    
    claim = sanitize(report_data.get("claim", ""))
    verdict = str(report_data.get("verdict", "UNKNOWN"))
    conf_str = str(report_data.get("confidence_score", "0%"))
    conf_val = int(conf_str.replace('%', '')) if '%' in conf_str else 0
    
    abstract_text = (
        f"This report investigates the following submitted claim: '{claim}'. "
        f"Utilizing advanced artificial intelligence and automated web scraping algorithms, "
        f"the system evaluated the veracity of the statement against retrieved digital evidence. "
        f"The verification pipeline concluded with a final verdict of {verdict}, yielding a "
        f"system confidence score of {conf_str}."
    )
    pdf.multi_cell(0, 6, txt=abstract_text, align="J")
    pdf.ln(8)
    
    # --- CHART GENERATION (Matplotlib) ---
    # THE FIX: Create temp files and immediately close the OS file descriptor to unlock them for Windows
    fd_pie, temp_pie_name = tempfile.mkstemp(suffix=".png")
    os.close(fd_pie)
    
    fd_bar, temp_bar_name = tempfile.mkstemp(suffix=".png")
    os.close(fd_bar)
    
    try:
        # 1. PIE CHART: Confidence vs Uncertainty
        plt.figure(figsize=(4, 4))
        labels = ['System Confidence', 'Uncertainty Margin']
        sizes = [conf_val, 100 - conf_val]
        colors = ['#4F81BD', '#D0CECE']
        plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
        plt.title('Algorithm Verdict Confidence')
        plt.tight_layout()
        plt.savefig(temp_pie_name, dpi=150)
        plt.close()
        
        # 2. HORIZONTAL BAR CHART: Source Relevance
        sources = report_data.get("evidence_sources", [])
        source_names = []
        source_scores = []
        for i, s in enumerate(sources[:5]): 
            name = s.get("source", f"Source {i+1}")
            score = s.get("similarity_score", 0.5)
            score = float(score) if score is not None else 0.5
            source_names.append(name[:15] + "..." if len(name) > 15 else name)
            source_scores.append(score)
            
        if not source_names:
            source_names = ["No Sources"]
            source_scores = [0]
            
        plt.figure(figsize=(6, 3))
        plt.barh(source_names[::-1], source_scores[::-1], color='#4F81BD', height=0.5)
        plt.xlabel('Relevance Score (0.0 - 1.0)')
        plt.title('Distribution of Source Relevance')
        plt.tight_layout()
        plt.savefig(temp_bar_name, dpi=150)
        plt.close()

        # --- INSERT CHARTS INTO PDF ---
        pdf.set_font("Times", "B", 12)
        pdf.cell(0, 8, txt="1. QUANTITATIVE ANALYSIS", ln=True)
        
        y_before_charts = pdf.get_y()
        pdf.image(temp_pie_name, x=15, y=y_before_charts, w=80)
        pdf.image(temp_bar_name, x=100, y=y_before_charts + 5, w=95)
        pdf.ln(85) 

    finally:
        # Clean up temporary images safely
        if os.path.exists(temp_pie_name):
            os.unlink(temp_pie_name)
        if os.path.exists(temp_bar_name):
            os.unlink(temp_bar_name)

    # --- METHODOLOGY FLOWCHART (Drawn with FPDF) ---
    pdf.set_font("Times", "B", 12)
    pdf.cell(0, 8, txt="2. METHODOLOGY & VERIFICATION PIPELINE", ln=True)
    pdf.set_font("Times", "", 10)
    pdf.multi_cell(0, 5, txt="The figure below illustrates the article selection and fact-checking flow process utilized by the Truth Intelligence engine to arrive at the final verdict.")
    pdf.ln(5)
    
    flow_x = 55
    current_y = pdf.get_y()
    
    steps = [
        "1. Claim Identification & Extraction",
        "2. Semantic Web Search & Source Retrieval",
        "3. Cross-Referencing & Context Analysis",
        f"4. Final Output: {verdict}"
    ]
    
    for step in steps:
        pdf.set_fill_color(240, 240, 240)
        pdf.rect(flow_x, current_y, 100, 10, 'DF')
        pdf.set_xy(flow_x, current_y + 2)
        pdf.cell(100, 5, txt=step, align='C')
        
        if step != steps[-1]: 
            pdf.line(flow_x + 50, current_y + 10, flow_x + 50, current_y + 18)
            pdf.line(flow_x + 48, current_y + 16, flow_x + 50, current_y + 18)
            pdf.line(flow_x + 52, current_y + 16, flow_x + 50, current_y + 18)
            current_y += 18
        else:
            current_y += 15
            
    pdf.set_y(current_y + 5)

    # --- EXPLANATION & REFERENCES ---
    pdf.set_font("Times", "B", 12)
    pdf.cell(0, 8, txt="3. QUALITATIVE EXPLANATION", ln=True)
    pdf.set_font("Times", "", 11)
    safe_exp = sanitize(report_data.get("explanation", ""))
    pdf.multi_cell(0, 6, txt=safe_exp, align="J")
    pdf.ln(8)
    
    pdf.set_font("Times", "B", 12)
    pdf.cell(0, 8, txt="4. REFERENCES", ln=True)
    pdf.set_font("Times", "", 10)
    
    for idx, item in enumerate(report_data.get("evidence_sources", []), start=1):
        source_name = sanitize(item.get("source", "UNKNOWN"))
        title = sanitize(item.get("title", "Link"))
        url = sanitize(item.get("url", "#"))
        citation = f"[{idx}] {source_name}. \"{title}.\" Retrieved from: {url}"
        pdf.multi_cell(0, 5, txt=citation)
        pdf.ln(3)
        
    return bytes(pdf.output())

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from multimodal.ocr_reader import extract_text_from_image

@st.cache_data(ttl=3600, show_spinner=False)
def fetch_verification_cached(claim_text: str) -> dict:
    """
    Sends claim text to backend API and caches response for 1 hour (3600s).
    Prevents repeated expensive verification API calls on UI re-renders.
    """
    response = requests.post(
        "http://localhost:8000/analyze",
        json={"input_type": "text", "content": claim_text},
        timeout=30
    )
    if response.status_code == 200:
        return response.json()
    else:
        raise RuntimeError(f"API returned error status code: {response.status_code}")

st.set_page_config(page_title="Truth Intelligence", layout="centered")
st.title("AI Fake News & Misinformation Verifier")

input_mode = st.radio("Choose Input Mode:", ["Direct Text Input", "Upload Image / Screenshot"], horizontal=True, key="input_mode_selector")
user_claim = ""

if input_mode == "Direct Text Input":
    user_claim = st.text_area("Enter suspicious statement or news claim:", height=120, key="direct_text_input")
else:
    uploaded_file = st.file_uploader("Upload image (e.g., WhatsApp notice, screenshot, circular):", type=["png", "jpg", "jpeg"], key="image_uploader_file") 
    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Image Preview", use_container_width=True)
        with st.spinner("Extracting text via OCR..."):
            extracted = extract_text_from_image(uploaded_file)
        if extracted:
            user_claim = st.text_area("Extracted Text (You can edit before verifying):", value=extracted, height=120, key="ocr_extracted_text_area")
        else:
            st.warning("No readable text detected in this image. You can type the claim manually below.")
            user_claim = st.text_area("Enter claim manually:", height=100, key="ocr_manual_fallback_text_area")  

if st.button("Verify Claim", type="primary"):
    cleaned_claim = user_claim.strip() if user_claim else ""
    if not cleaned_claim:
        st.warning("Please provide a valid claim or upload an image containing text.")
    else:
        with st.spinner("Running verification pipeline against web sources..."):
            try:
                # Call cached backend function
                data = fetch_verification_cached(cleaned_claim)

                st.divider()

                verdict = data.get("verdict", "UNKNOWN")
                confidence_pct = int(data.get("confidence", 0) * 100)

                if verdict == "SUPPORTED":
                    st.success(f"### VERDICT: {verdict}")
                elif verdict == "REFUTED":
                    st.error(f"### VERDICT: {verdict}")
                elif verdict == "CONFLICTING":
                    st.warning(f"### VERDICT: {verdict}")
                else: 
                    st.info(f"### VERDICT: {verdict}")

                st.write(f"**Confidence Score:** {confidence_pct}%")
                st.write(f"**Explanation:** {data.get('reason')}")

                st.divider()
                st.subheader("Retrieved Evidence & Sources")
                evidence_list = data.get("evidence", [])
                if evidence_list:
                    for idx, item in enumerate(evidence_list, start=1):
                        source_tag = item.get("source", "UNKNOWN")
                        title = item.get("title", "Source Link")
                        url = item.get("url", "#")
                        snippet = item.get("snippet", "No preview available.")
                        score = item.get("similarity_score", None)

                        score_str = f" | *Relevance Score: {score}*" if score is not None else ""
                        st.markdown(f"**{idx}. [{source_tag}]** [{title}]({url}){score_str}")
                        st.caption(snippet)

                    # --- PHASE 3 / PHASE 4: REPORT EXPORTING FEATURE ---
                    st.divider()
                    st.subheader("Export Verification Report")
                    
                    # Prepare report content structures
                    report_data = {
                        "timestamp": datetime.datetime.now().isoformat(),
                        "claim": user_claim.strip(),
                        "verdict": verdict,
                        "confidence_score": f"{confidence_pct}%",
                        "explanation": data.get('reason'),
                        "evidence_sources": evidence_list
                    }

                    # Format as clean Markdown text block for easy reading/downloading
                    md_lines = [
                        "# Truth Intelligence - Verification Report",
                        f"**Date:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                        f"**Claim:** {user_claim.strip()}",
                        f"**Verdict:** {verdict}",
                        f"**Confidence Score:** {confidence_pct}%",
                        f"\n## Explanation\n{data.get('reason')}",
                        "\n## Retrieved Sources"
                    ]
                    for idx, item in enumerate(evidence_list, start=1):
                        md_lines.append(f"{idx}. **[{item.get('source', 'UNKNOWN')}]** [{item.get('title', 'Link')}]({item.get('url', '#')})")
                        md_lines.append(f"   > {item.get('snippet', '')}")
                    
                    markdown_report = "\n".join(md_lines)

                    col1, col2, col3 = st.columns(3)
                    with col1:
                        st.download_button(
                            label="Download as JSON",
                            data=json.dumps(report_data, indent=4),
                            file_name=f"verification_report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.json",
                            mime="application/json"
                        )
                    with col2:
                        st.download_button(
                            label="Download as Markdown",
                            data=markdown_report,
                            file_name=f"verification_report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.md",
                            mime="text/markdown"
                        )
                    with col3:
                        # Pass the structured dictionary instead of the markdown string
                        pdf_bytes = create_pdf(report_data) 
                        st.download_button(
                            label="Download as PDF",
                            data=pdf_bytes,
                            file_name=f"verification_report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
                            mime="application/pdf"
                        )

                else:
                    st.write("No external evidence links returned.")

            except Exception as e:
                st.error(f"Failed to connect to backend server: {e}")